from fpdf import FPDF
import datetime
import os


def generateQuotePdf(brief: str, agentOutput: str, filename: str = "quote.pdf") -> str:
    """Turn the agent's text output into a clean PDF quote."""

    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_fill_color(30, 30, 30)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 15, "SALES QUOTATION", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    # Date and ref
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Generated: {datetime.datetime.now().strftime('%d %B %Y, %I:%M %p')}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Client brief
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Client Brief:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_fill_color(245, 245, 245)
    pdf.multi_cell(0, 7, brief, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Agent output
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Proposed Solution & Quote:", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 6, agentOutput, new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "This quote was generated by an AI Sales Agent. Prices subject to availability.",
             align="C", new_x="LMARGIN", new_y="NEXT")

    outputPath = os.path.join(os.getcwd(), filename)
    pdf.output(outputPath)
    print(f"\n📄 PDF saved to: {outputPath}")
    return outputPath


if __name__ == "__main__":
    # Quick test
    generateQuotePdf(
        brief="Minimalist home office under RM3,000 in KL",
        agentOutput="Sample quote output here...",
        filename="test_quote.pdf"
    )